//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativaGaragem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Carro
    {
        public Carro()
        {
            this.Solicitacao = new HashSet<Solicitacao>();
            this.Vaga = new HashSet<Vaga>();
        }
        [Key]
        public long IDCarro { get; set; }
        public string Modelo { get; set; }
        public string Montadora { get; set; }
        public string Placa { get; set; }
        public string Ano { get; set; }
        public long IDGaragem { get; set; }
        public long IDCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Garagem Garagem { get; set; }
        public virtual ICollection<Solicitacao> Solicitacao { get; set; }
        public virtual ICollection<Vaga> Vaga { get; set; }
    }
}
