//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativaGaragem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Carro = new HashSet<Carro>();
            this.Pagamento = new HashSet<Pagamento>();
        }
        [Key]
        public long IDCliente { get; set; }
        public string Endereco { get; set; }
        public long IDUsuario { get; set; }
    
        public virtual ICollection<Carro> Carro { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
