//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativaGaragem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Garagem
    {
        public Garagem()
        {
            this.Carro = new HashSet<Carro>();
            this.Vaga = new HashSet<Vaga>();
        }
        [Key]
        public long IDGaragem { get; set; }
        public string Nome { get; set; }
        public byte QuantidadeVagas { get; set; }
        public byte QuantidadeVagasLivres { get; set; }
        public string Endereco { get; set; }
    
        public virtual ICollection<Carro> Carro { get; set; }
        public virtual ICollection<Vaga> Vaga { get; set; }
    }
}
