//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativaGaragem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Limpeza
    {
        public Limpeza()
        {
            this.Realizacao = new HashSet<Realizacao>();
            this.Solicitacao = new HashSet<Solicitacao>();
        }
        [Key]
        public long IDLimpeza { get; set; }
        public string Tipo { get; set; }
        public float Valor { get; set; }
        public bool StatusAprovacao { get; set; }
        public System.DateTime DataSolicitacao { get; set; }
        public System.DateTime DataExecucao { get; set; }
        public bool SituacaoExecucao { get; set; }
    
        public virtual ICollection<Realizacao> Realizacao { get; set; }
        public virtual ICollection<Solicitacao> Solicitacao { get; set; }
    }
}
