//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativaGaragem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Pagamento
    {
        [Key]
        public long IDPagamento { get; set; }
        public string FormaPagamento { get; set; }
        public System.DateTime DataPagamento { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public float Valor { get; set; }
        public long IDCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
