//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativaGaragem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Vaga
    {
        [Key]
        public long IDVaga { get; set; }
        public long IDCarro { get; set; }
        public long IDGaragem { get; set; }
    
        public virtual Carro Carro { get; set; }
        public virtual Garagem Garagem { get; set; }
    }
}
